$.start.$ = trustworthiness-vector / trust-tier / verifier-id
trustworthiness-vector = ({
        ? instance-identity-label => trustworthiness-claim,
        ? configuration-label => trustworthiness-claim,
        ? executables-label => trustworthiness-claim,
        ? file-system-label => trustworthiness-claim,
        ? hardware-label => trustworthiness-claim,
        ? runtime-opaque-label => trustworthiness-claim,
        ? storage-opaque-label => trustworthiness-claim,
        ? sourced-data-label => trustworthiness-claim,
    }) .within ({+ any => any})
instance-identity-label = "instance-identity" .feature "json" / 0 .feature "cbor"
configuration-label = "configuration" .feature "json" / 1 .feature "cbor"
executables-label = "executables" .feature "json" / 2 .feature "cbor"
file-system-label = "file-system" .feature "json" / 3 .feature "cbor"
hardware-label = "hardware" .feature "json" / 4 .feature "cbor"
runtime-opaque-label = "runtime-opaque" .feature "json" / 5 .feature "cbor"
storage-opaque-label = "storage-opaque" .feature "json" / 6 .feature "cbor"
sourced-data-label = "sourced-data" .feature "json" / 7 .feature "cbor"
trustworthiness-claim = -128 .. 127
trust-tier-none-label = "none" .feature "json" / 0 .feature "cbor"
trust-tier-affirming-label = "affirming" .feature "json" / 2 .feature "cbor"
trust-tier-warning-label = "warning" .feature "json" / 32 .feature "cbor"
trust-tier-contraindicated-label = "contraindicated" .feature "json" / 96 .feature "cbor"
trust-tier /= trust-tier-none-label / trust-tier-affirming-label / trust-tier-warning-label / trust-tier-contraindicated-label
verifier-id = {
  developer-label => text,
  build-label => text,
}
developer-label = "developer" .feature "json" / 0 .feature "cbor"
build-label = "build" .feature "json" / 1 .feature "cbor"
